# Generated by Django 4.2.11 on 2026-01-18 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='年龄')),
                ('major', models.CharField(max_length=100, verbose_name='专业名称')),
                ('enrollment_date', models.DateField(verbose_name='入学时间')),
                ('graduation_date', models.DateField(verbose_name='毕业时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['student_id'],
            },
        ),
    ]
