# Generated by Django 4.2.11 on 2026-05-29 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='院系名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='院系编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
                'ordering': ['code'],
                'permissions': [('can_manage_department', '可以管理院系')],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'permissions': [('can_manage_student', '可以管理学生')], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(10)], verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='students.department', verbose_name='所属院系')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'ordering': ['teacher_id'],
                'permissions': [('can_manage_teacher', '可以管理教师')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True, verbose_name='课程编号')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('credit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='学分')),
                ('description', models.TextField(blank=True, default='', verbose_name='课程描述')),
                ('max_students', models.PositiveIntegerField(default=60, verbose_name='最大学生数')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='students.department', verbose_name='开课院系')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='students.teacher', verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['course_id'],
                'permissions': [('can_manage_course', '可以管理课程')],
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('grade_year', models.PositiveIntegerField(verbose_name='入学年份')),
                ('advisor', models.CharField(blank=True, default='', max_length=50, verbose_name='班主任')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='students.department', verbose_name='所属院系')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['department', 'grade_year', 'name'],
                'permissions': [('can_manage_class', '可以管理班级')],
                'unique_together': {('name', 'department', 'grade_year')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('delete', '删除')], max_length=10, verbose_name='操作')),
                ('model_name', models.CharField(max_length=50, verbose_name='模型名称')),
                ('object_id', models.CharField(max_length=50, verbose_name='对象ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='对象描述')),
                ('changes', models.TextField(blank=True, default='{}', verbose_name='变更内容 (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.classinfo', verbose_name='班级'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='如 2025-2026-1', max_length=20, verbose_name='学期')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='成绩')),
                ('grade_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='绩点')),
                ('status', models.CharField(choices=[('enrolled', '在修'), ('dropped', '退选'), ('completed', '已完成')], default='enrolled', max_length=10, verbose_name='状态')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'ordering': ['-semester', 'student'],
                'permissions': [('can_manage_grade', '可以管理成绩')],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('status', models.CharField(choices=[('present', '出勤'), ('late', '迟到'), ('absent', '缺勤'), ('leave', '请假')], default='present', max_length=10, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'ordering': ['-date', 'student'],
                'permissions': [('can_manage_attendance', '可以管理考勤')],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
